### ISSUE TITLE
EMS Tahoe Handling

### ISSUE THREAD

**Issue by tris203** [heyjeay/kudosrp-public#1]
Car rolls when turning

**Comment by Chilllyyy** [comment]
This was fixed,
8b3348081ff4da85c0150e71c54c3df92ab57631
82e38c6195ac16040c60628707e85d04db93ca15

**Comment by Chilllyyy** [comment]
This was fixed in,

https://github.com/heyjeay/kudos-vehicles/commit/8b3348081ff4da85c0150e71c54c3df92ab57631
